### ISSUE TITLE
Raster maps with rivers but no dashed areas

### ISSUE THREAD

**Issue by Equationist** [nvkelso/natural-earth-raster#2]
It would be nice to have a raster map including rivers but without the areas enclosed by dashed lines (e.g. many prominent in Iran), similar to the rasters that Tom Patterson has at shadedrelief.com but at 1:10m scale.

**Comment by nvkelso** [comment]
Please use software like QGIS, ArcGIS, GeographicImager, or Natural Scene Designer to accomplish this.
