### ISSUE TITLE
Generation Scripts?

### ISSUE THREAD

**Issue by four43** [nvkelso/natural-earth-raster#4]
Are there scripts to generate these somewhere? Any interest in such a thing? 

Are they able to be rendered at a higher resolution?

Incredible project, thank you!

**Comment by nvkelso** [comment]
No scripts to share. Instead these are backed by custom Photoshop documents with manual pre-processing, touch up adjustments, and blending.

**Comment by four43** [comment]
Fair enough, thanks!
